### ISSUE TITLE
On languages overview page of a project: Add a checkbox to "Show only active translations"

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#10]
With all those languages we now have, many will stay empty and only make the list of translations long.
Add a "Show only active translations" chackbox to flter out the empty ones.

**Comment by KapiX** [comment]
What do you think using browser's language preferences to single out preferred languages to the top and display all the other ones below?

**Comment by humdingerb** [comment]
Not sure. My preferred language should be English, even though the language I'd be translating is German. Also, the developer might like like to hide all un-active languages, not just sort "his" language to the top.
