### ISSUE TITLE
Add button to export a ZIP archive of all active catkeys of a project

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#13]
Saves having to export each language individually.

**Comment by humdingerb** [comment]
The file name should contain the fingerprint, e.g. "Clipdinger_all_catkeys_453677281.zip".

**Comment by KapiX** [comment]
It will only export languages set for the project (in Edit project panel).

**Comment by humdingerb** [comment]
I thought the "Edit " project panel where you can set languages is to be removed, because every project always gets all available languages anyway (of which most will remain empty/inactive)?

The Zip-export could just include all active (progress > 0%) languages.

Otherwise, you may wonder why your Zip-export doesn't contain a certain language that is active, if you forgot to set it on the "Edit" project panel.
