### ISSUE TITLE
Add more meta data to projects

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#15]
When creating/editing a project's en.catkeys ("Application | Edit") additional data could be added:
* a 32 bit icon (defaulting to Haiku's three colour cubes)
* the URL to the project home page
* the URL to the project issue tracker

The icon can then be used whereever here's currently only the project name. This can help not to get confused, if e.g. there are several slightly similarly named projects, like "PecoRename" and "PecoBeat".
The URLs can be added to small icons after the project's name, to give quick access, e.g. if a translator found a typo. Add a tooltip to those icons "Project's website", Project's bugtracker".

Here's a mockup:

![en catkeys-edit](https://user-images.githubusercontent.com/6107158/35614801-8a71397e-0670-11e8-9fa0-ebebda3cbd73.png)

**Comment by humdingerb** [comment]
Hmm... maybe even add an optional URL for downloading a special pre-release the translators can install, because the app being translated hasn't been released yet. Translation is much easier when not done blindly...
That would add another icon to the project and bugtracker one.

**Comment by humdingerb** [comment]
Also, a text box where a dev can give additional info that'll be displayed on the "Files" and "Translation" pages. Could be used to communicate what has changed with the latest en.catkeys update, for example.
Should be limited to 500 characters or somethins sensible.

**Comment by KapiX** [comment]
I am not convinced by the text box for additional info. Is this info really relevant to translators?

**Comment by humdingerb** [comment]
I'm not exactly sure either anymore... :)

BTW, for that release date (is that te planned date for the next release?) a date-picker-wdget would be nice. Until then, or maybe instead if it's not trivial, insert the format "YYYY-MM-DD" as start value intot he textbox.

**Comment by KapiX** [comment]
It's date of next release. It wouldn't make much sense otherwise ;) Date picker-widget is available in browsers which support input type="date".

**Comment by humdingerb** [comment]
Such a date picker is available at the Haiku forums when pinning a topic (admin feature) for both web+ and qupzilla. Dunno how that's implemented though...

Maybe add "Next release date" anyway, to make it clear to morons like me even. :)
