### ISSUE TITLE
Mockups for design improvements

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#16]
Here are a few ideas for consideration when time allows.

### The start page - "Projects":

![project](https://user-images.githubusercontent.com/6107158/35614946-034808fa-0671-11e8-937c-00054d9e79a8.png)

Material-icons top right: help, settings, login/profile
The list of available projects shows meta data: 32px icon, icons to link to project website and bugtracker.

### Project - "Files":

![project-files](https://user-images.githubusercontent.com/6107158/35615126-8927d87e-0671-11e8-8a8f-763183297bf7.png)

### Project - "Application" - translation page:

![translation](https://user-images.githubusercontent.com/6107158/35615221-c7bf9f7c-0671-11e8-97c4-4a4bdb1370dd.png)

Flag of current language at top right.

### Project - "Application - Edit":

![en catkeys-edit](https://user-images.githubusercontent.com/6107158/35615303-0758db6c-0672-11e8-822e-9a26768f456d.png)

As described in #15.

**Comment by KapiX** [comment]
Implemented in 4cea484fd286158f058c2b37c67b9f503981c6ef.
