### ISSUE TITLE
Add "Needs work" status to each project on the "Home" page

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#18]
If the list of available projects on the starting page had after each project a list of languages that are active (>0%) but incomplete (<100%), one could quickly spot which projects' languages need work.
That way one can also quickly see which formerly "complete" projects must've gotten an update.

E.g.: `Clipdinger (Needs work: de, fr, it, uk)`

The text in brackets in grey instead of black, but IMO much better would be to use 16px flags instead. You'll spot your country's flag much quicker than parsing text abbreviations.

(Should the layout change as in #16, this could be in a 2nd column "Needs work".
BTW, the term "Needs work" is a bit awkward here, but it does fit well with the checkbox in the translation blocks. Therefore I'd stick to the term wherever it appears to avoid confusion.)

**Comment by KapiX** [comment]
What do you think about each user having language preference, and if the language(s) in a project need to be completed it gets a badge with information about that? Would that work or am I missing the intention?

**Comment by humdingerb** [comment]
That would even be preferred, I think. The above was just an idea since there aren't user settings yet. Once there are, people could even enter their email address and subscribe to be notified whenever there's a an app where their language is <100%.

**Comment by KapiX** [comment]
Implemented in 6bf021e8c8de7751751e754d7eb417c342f7eace.
