### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#20]
I've attached [Polyglot_documentation.zip](https://github.com/KapiX/Polyglot/files/1690498/Polyglot_documentation.zip) that contains htmlified docs for translators, developers and an index page that doubles as about page. It contains part of the css I usually use for docs, just to make it less bland.
I think it's better to put into this ticket than mailing stuff around.

As the site changes, things will have to be updated, esp. the screenshots I guess. Once you "twig" the html, I should be able to PR those changes and everything you'd like to have improved.

Please have a look at the "Overview" section of the _Help_dev.html_ to see if I got the gist right. I'm not really familiar with databases and the terminology could be off (speaking of adding "fields" for example). You may be able to express the workings more clearly than me...

No hurry, of course.

**Comment by KapiX** [comment]
Implemented in f8785e5775fff86f73339f625eed08314e07d8b4.
