### ISSUE TITLE
Users can't enter projects any more

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#28]
This used to work until recently.
See the forum thread https://discuss.haiku-os.org/t/help-translating-applications-with-polyglot/6548/8 :

> I can enter into the site, but when select one of the different apps available from the list, I get the message:  "Whoops, looks like something went wrong."

**Comment by KapiX** [comment]
Should be fixed with f2a36491b1b5a3baadeab11ea7bfcd06cd3e372d.
