### ISSUE TITLE
On a project's "Files" page, prefix language ISO to language name

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#3]
This would have the sorting of the languages as the catkeys files are in the "locales" folder in Tracker. Add a nice flag to make it pretty. (I could create the PNGs from out flags icons and make a PR, if you want :))

**Comment by KapiX** [comment]
Please do :)

**Comment by KapiX** [comment]
Fixed in da3150e4691ff01c127d4db3fea0f5934c0ee416.
