### ISSUE TITLE
Uploading en.catkeys fails for an app's "Administrator"

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#30]
janus is "Administrator" for Slayer, as he added the Slayer project after I upgraded his Polyglot role to "Developer". He tried to upload an updated en.catkeys for Slayer, but got the "Whoops, looks like something went wrong" error.
I, OTOH, had no problems uploading the new Slayer en.catkeys.

**Comment by KapiX** [comment]
I cannot reproduce this, and I don't see any indication of this ever happening in the logs (last entry is from 26-02-2018). For now let's assume it was an intermittent issue. If it happens again, please reopen this ticket.

**Comment by janus2** [comment]
Still happening the error message:
![error](https://user-images.githubusercontent.com/10423645/37251213-f2187f24-250b-11e8-85fd-535976ee3f3c.png)
The en.catkeys file:

[en.catkeys.txt](https://github.com/KapiX/Polyglot/files/1800132/en.catkeys.txt)

I have tried with Web+ (Haiku), Yandex and Safari (macOs)

**Comment by KapiX** [comment]
Should be fixed with 3363ebdc426720eb915070687693d517330df5ab.
