### ISSUE TITLE
rewelacyjny program

### ISSUE THREAD

**Issue by letarg0** [KapiX/Polyglot#44]
Bardzo ciekawie wygląda. Bardzo dobry pomysł. 

Czy jest możliwość wprowadzenia sugestii i dyskusji?
Na stronach https://tatoeba.org/pol/ (swoja drogą polecam i może nawet zastanowić się nad integracją) są komentarze do każdego tłumaczenia. Czasem to pomaga, bo autor często sam by zmienił, a ktoś może zostawić wiadomość.

Można by też zrobić sugestie anonimowe by bez logowania ktoś mogl zostawić informacje dla tlumacza. Niestety od razu może pojawić się spam.

Czy jest gdzieś jakiś sposób by zintegrowac to z własnym oprogramowaniem? Powiedzmy, ktoś ma swój program i chciałby postawic u siebie tłumaczenie

**Comment by KapiX** [comment]
Sugestie są w planach.
Sugestii anonimowych i dyskusji raczej nigdy nie będzie.
Co do tatoeby integracja jest do rozważenia, ale mam wątpliwości czy będzie przydatna w kontekście tłumaczenia programów.
Stawianie z własnym oprogramowaniem: instrukcje w README powinny załatwić sprawę, ale czy to ma sens nie wiem. Polyglot został zaprojektowany do współpracy z formatem tłumaczeń Haiku i tylko z nim (co jest też odzwierciedlone w strukturze bazy). Poza tym podstawowe założenie to kilka *małych* projektów na jednej instancji. Jeżeli masz jeden projekt, który chcesz przetłumaczyć, to więcej sensu będzie miało postawienie Pootle, Weblate, itp. które są systemami bardziej dojrzałymi i rozwijanymi (dla kontrastu: ja nie mam zbyt wiele czasu, więc nowe funkcjonalności będą dodawane powoli lub wcale).

**Comment by KapiX** [comment]
> Ale za to mogą być lepiej zintegrowane. np. denerwuje mnie menu czesciowo przetlumaczone w trackerze.
> Wszystko po polsku ale Applications, Preference juz nie tylko 3 wpisy i nie wiem jak mialbym to poprawic samodzielnie.

Tłumaczenie Haiku nie odbywa się na Polyglocie. Polyglot służy twórcom aplikacji.

> Skoro juz tyle zrobiłes to **tylko** dodanie stron www nie powinno być problemem.

Chyba nie zdajesz sobie sprawy ile pracy może być zawarte w „tylko”. *Nieodpłatnej* pracy, za którą często nie usłyszy się nawet dziękuję.

> Te inne programy nie zawsze są darmowe.

Pootle i Weblate są.

Jeżeli masz sugestie dotyczące tłumaczenia Haiku to odpowiednim miejscem do zgłoszenia problemu jest: https://dev.haiku-os.org

https://i18n.haiku-os.org/pootle to system używany do tłumaczenia systemu.

**Comment by letarg0** [comment]
musialbym zalozyc konto, itd. nie wiem czy dla 3 wpisow warto https://i18n.haiku-os.org/pootle
