### ISSUE TITLE
Glossary: Add headers to text boxes in "new entry" page

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#63]
While it should be obvious which column is for the original and which is for the translated text, adding a title above those text boxes may be a good idea. Should be the same as on the actual Glossary index page. There it is now "Text" and "Translation".
Maybe those can be changed to "Original text" and e.g. "Polish translation", to make add another indicator in which Glossary we are.

**Comment by KapiX** [comment]
Textareas have placeholders to indicate their purpose, is that not enough?

**Comment by humdingerb** [comment]
Indeed it is. I could've sworn that I didn't see those when going to that page... Closing then.
