### ISSUE TITLE
Allow exporting all/finished catkeys of multi-module projects

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#66]
If a project has several 'modules' - like Pecorename (Application and Add-on) - you cannot export all/finished catkeys for the whole project. It errors with:

> There are duplicate file paths. Cannot generate an archive.

Maybe create the two "locales" folders in subfolders named after the modules before zipping it all up.

**Comment by KapiX** [comment]
This is working as expected. PecoRename modules should have different paths set - Application should be "Main/locales/%lang%.catkeys" and Add-on "Tracker Add-On/locales/%lang%". I have changed them and successfully generated an archive.
The idea is you grab the archive and drop it in the root of the project without further changes.

**Comment by humdingerb** [comment]
Ah alright... bug sitting in front of the monitor again... :)
