### ISSUE TITLE
Add Canadian and Australian English

### ISSUE THREAD

**Issue by jt15s** [KapiX/Polyglot#68]
Would be good if Canadian and Australian English were added to Polyglot.

I note that Canadian English is present in the Polyglot profile, where it appears in the "Preferred Language" selection list, but it doesn't seem to show up as a translation to complete when clicking on an application to translate?

Thanks in advance!

**Comment by KapiX** [comment]
Australian added.

It doesn't show up, because there are no translations yet. There is "Show all languages" link at the top left corner of the table.

I recommend reading excellent Help pages contributed by Humdinger. :)
