### ISSUE TITLE
Add per language global default translations

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Polyglot#9]
Probably a bigger fish...
It would be nice if each language had a list of default translations for the standard stuff, like `OK, Quit, Close, Abort, Cancel, Defaults, Revert...`
Would cut down work and increase consistency.

**Comment by KapiX** [comment]
Glossaries added in 53d66d6d13444fdd1e955284fcb8e04a6a947204.
Pretranslation (which will make use of them) will come soon.

**Comment by humdingerb** [comment]
Nice! Do I understand correctly:
The "Only full phrases should be added here, no partial matches." meaning that it'll work only for 100% matches and the word(s) will be replaced 1:1 from what's in the "Glossary". The Glossary is not like the "Terminology" at https://dev.haiku-os.org/wiki/i18n/de_DE/Terminology , where there are sometimes explanations on how something is to be translated.

**Comment by humdingerb** [comment]
One more thing: How are ellipsis handled? I suppose, those could be ignored?

**Comment by KapiX** [comment]
> it'll work only for 100% matches and the word(s) will be replaced 1:1 from what's in the "Glossary".

Yes.

> The Glossary is not like the "Terminology" at https://dev.haiku-os.org/wiki/i18n/de_DE/Terminology , where there are sometimes explanations on how something is to be translated.

It could be made that way but I'm not sure if there is value in that right now.

> How are ellipsis handled? I suppose, those could be ignored?

They aren't handled at all right now because pretranslations are not implemented, but it's a good point.
To be sure I understand correctly: you mean treating … (one character) and ... (three dots) as if they are the same?

**Comment by humdingerb** [comment]
>  I'm not sure if there is value in that [Termnology] right now.

Agreed.

> you mean treating … (one character) and ... (three dots) as if they are the same?

That, and with/without ellipsis and other punctuation like colons. Colons often appear in text control labels, and the same term without punctuation in buttons etc. ("Save...", Save").

**Comment by KapiX** [comment]
Pretranslation available in the menu. People using the feature will be added as authors of the specific translation (for bookkeeping), but will not be added as contributor to the project (the table below the languages) - the translations are not theirs and they just clicked the button :).

**Comment by humdingerb** [comment]
Very good! I'll look into updating the documentation soon.

**Comment by KapiX** [comment]
What I forgot to mention is I have actually implemented punctuation separation (help is already updated), so you might want to remove it from German glossary.

**Comment by humdingerb** [comment]
OK. That means puntuation (ellipsis, colon etc.) are ignored, right?

**Comment by KapiX** [comment]
Yes, but it only works one way:

- Text: "Add:" Glossary: "Add" will match and return "Dodaj:"
- Text: "Add" Glossary: "Add:" - no match

**Comment by humdingerb** [comment]
Got it.
